### ISSUE TITLE
TabStops的问题

### ISSUE THREAD

**Issue by mingancai** [lsjwzh/FastTextView#3]
下载你的源码中TabStops这个类不存在，android.text.Layout类中的内部类？查看源码并没有找到，希望得到源主的解答，谢谢啦。

**Comment by mingancai** [comment]
@lsjwzh 另外，现在readmore展开之后会原文会少一个字符，本想看看源码，并修复下这个问题，但是以上问题导致编译不通过，希望题主帮助下在下，谢谢

**Comment by lsjwzh** [comment]
编译需要参考这个
https://github.com/anggrayudi/android-hidden-api
使用这里面的android.jar替换adnroid sdk里面的adnroid.jar

**Comment by lsjwzh** [comment]
多谢提issue。readmore那个问题我刚解决了一下。谢谢啦
