### ISSUE TITLE
TextStyle support

### ISSUE THREAD

**Issue by avently** [lsjwzh/FastTextView#9]
Hello. Great lib, so fast.  The problem is that I'm unable to use TextStyle attribute. Can you support it too? I need to make text bold but this attribute is ignored.

**Comment by avently** [comment]
Found how to do it programmatically:
textView.paint.typeface = Typeface.create("sans-serif-condensed", Typeface.BOLD)
Maybe would be a good idea to provide methods like setTextColor in your main class FastTextView but if you don't think so this issue can be closed.

**Comment by lsjwzh** [comment]
thx for your suggest. i will support TextStyle  soon
